version: '2'
networks:
  dataverse_network:
    external:
      name: nginxproxynetwork

services:
  postgresql:
    container_name: postgresql
    image: library/postgres:10.13
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - "LC_ALL"
      - "POSTGRES_DB=dataverse"
      - "POSTGRES_USER=dataverse"
      - "POSTGRES_PASSWORD=changeme"
      - "POSTGRES_PORT=5432"
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data
    networks:
      - dataverse_network

  solr:
    container_name: solr
    image: iqss/solr-k8s
    env_file:
      - .env
    environment:
      # log4j patch
      - "SOLR_OPTS=-Dlog4j2.formatMsgNoLookups=true"
    volumes:
      - ./data/solr_data:/opt/solr/server/solr/collection1/data
    networks:
      - dataverse_network

  dataverse:
    container_name: dataverse
    user:
      "root"
    build:
      context: .
      dockerfile: ./docker/dataverse-k8s/payara/Dockerfile
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
    depends_on:
      - postgresql
      - solr
    volumes:
      - ./data/dataverse_data:/data
      - ./personas/docker-compose/secrets:/secrets
    ports:
      - "8080:8080"
    networks:
      - dataverse_network
